# Generated by Django 5.2.4 on 2025-07-23 16:51

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_developer_group(apps, schema_editor):
    # Create the Developer group
    developer_group, created = Group.objects.get_or_create(name='Developer')
    if created:
        # Assign all permissions to the Developer group
        permissions = Permission.objects.all()
        developer_group.permissions.set(permissions)

def remove_developer_group(apps, schema_editor):
    # Remove the Developer group
    try:
        developer_group = Group.objects.get(name='Developer')
        developer_group.delete()
    except Group.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers"),
    ]

    operations = []
