# Generated by Django 5.2.4 on 2025-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20250723_1751"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="class_level",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="session",
        ),
        migrations.RemoveField(
            model_name="school",
            name="subscription_expires",
        ),
        migrations.RemoveField(
            model_name="school",
            name="subscription_plan",
        ),
        migrations.DeleteModel(
            name="FeePayment",
        ),
        migrations.DeleteModel(
            name="FeeStructure",
        ),
    ]
