# Generated by Django 4.2 on 2025-07-17 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_comment_post_idx_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key as UUID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='groups', to='core.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key as UUID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('accepted', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='core.studentprofile')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='core.studentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['from_student'], name='idx_conn_from'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['to_student'], name='idx_conn_to'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_student', 'to_student')},
        ),
    ]
